"""Initial database schema

Revision ID: 658ebfd64120
Revises: 
Create Date: 2025-11-20 01:36:05.790900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658ebfd64120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_telegram_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('idx_telegram_tokens_revoked'))
        batch_op.drop_index(batch_op.f('idx_telegram_tokens_token'))
        batch_op.drop_index(batch_op.f('idx_telegram_tokens_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_telegram_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_telegram_tokens_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('idx_telegram_tokens_revoked'), ['revoked'], unique=False)
        batch_op.create_index(batch_op.f('idx_telegram_tokens_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###
