"""Dump admin route inventory as Markdown. Used by Task 1 of 2026-05-24-admin-audit."""
import inspect
import logging
import os
import sys
from collections import defaultdict
from pathlib import Path

os.environ.setdefault("FLASK_ENV", "testing")
logging.disable(logging.CRITICAL)
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import create_app  # noqa: E402

ADMIN_BLUEPRINT_PREFIXES = (
    "admin",
    "admin_curriculum",
    "activity_admin",
    "audio_admin",
    "audit_admin",
    "book_admin",
    "collection_admin",
    "curriculum_admin",
    "grammar_lab_admin",
    "seo_admin",
    "settings_admin",
    "system_admin",
    "topic_admin",
    "user_admin",
    "word_admin",
)


def main() -> None:
    app = create_app()
    rules = []
    with app.app_context():
        for rule in app.url_map.iter_rules():
            if not rule.endpoint.startswith(ADMIN_BLUEPRINT_PREFIXES):
                continue
            view = app.view_functions.get(rule.endpoint)
            if view is None:
                continue
            wrappers = []
            cur = view
            while cur is not None and len(wrappers) < 10:
                wrappers.append(getattr(cur, "__qualname__", getattr(cur, "__name__", "?")))
                cur = getattr(cur, "__wrapped__", None)
            try:
                src = inspect.getsourcefile(view) or "?"
            except TypeError:
                src = "?"
            rules.append({
                "endpoint": rule.endpoint,
                "rule": str(rule),
                "methods": sorted(m for m in rule.methods if m not in ("HEAD", "OPTIONS")),
                "view": view.__name__,
                "module": view.__module__,
                "wrappers": wrappers,
                "source": src,
            })

    grouped = defaultdict(list)
    for r in rules:
        bp = r["endpoint"].split(".", 1)[0]
        grouped[bp].append(r)

    lines = [
        "# Admin URL Map",
        "",
        "Generated by `scripts/_audit_dump_admin_routes.py` for Task 1 of"
        " `docs/plans/2026-05-24-admin-full-audit.md`. Snapshot of every route"
        " under admin-related blueprints with method, endpoint, view, module and"
        " decorator-wrapper chain.",
        "",
    ]
    for bp in sorted(grouped):
        lines.append(f"## Blueprint: {bp}")
        lines.append("")
        lines.append("| Methods | URL | Endpoint | View | Module | Wrappers |")
        lines.append("|---|---|---|---|---|---|")
        for r in sorted(grouped[bp], key=lambda x: x["rule"]):
            m = ",".join(r["methods"])
            w = " -> ".join(r["wrappers"])
            lines.append(
                f"| {m} | `{r['rule']}` | `{r['endpoint']}` | {r['view']} | {r['module']} | {w} |"
            )
        lines.append("")

    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
